title: Karla Ramirez-Ruiz
logo: /assets/1695131843005.jfif  # Replace with the path to your image in your repo
description: Ecologist, MSc.

email: kcramirezruiz@gmail.com

# show_downloads: true

theme: jekyll-theme-cayman

# Optional: Add social media contact
social:
  linkedin: https://www.linkedin.com/in/karla-ramirez-ruiz/
  twitter: https://twitter.com/yourusername
  github: https://github.com/yourusername
  # Add others as needed
