title: Karla Ramirez-Ruiz
logo: /assets/1695131843005.jfif  # Replace with the path to your image in your repo
description: Ecologist, MSc.

email: kcramirezruiz@gmail.com

show_downloads: true

theme: jekyll-theme-cayman

social:
  linkedin: https://www.linkedin.com/in/karlarr/
  Google Scholar: https://scholar.google.com/citations?hl=es&user=DchdX-AAAAAJ&view_op=list_works
  ResearchGate: https://www.researchgate.net/profile/Karla-Ramirez-Ruiz?ev=prf_overview
  github: https://github.com/yourusername
  # Add others as needed

